apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          # Set image property to the Docker image name built previously
          # If image is already pushed to Azure Container Registry, set the full image name and tag
          image: {{ .Values.containerImage }}
          ports:
            - containerPort: 80
          env:
            - name : APP_KEY
              value : base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
          # If you want to use local Docker image, set IfNotPresent to imagePullPolicy
          imagePullPolicy: IfNotPresent


